// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB18Zan0SkmMJdPEHGf50EqXYPdztiIOI',
    appId: '1:280893152424:web:7e5980472f66489271b69d',
    messagingSenderId: '280893152424',
    projectId: 'padchat-4250a',
    authDomain: 'padchat-4250a.firebaseapp.com',
    storageBucket: 'padchat-4250a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTkdDVbuASSGwUiKc-81a3vpLzQU48k4',
    appId: '1:280893152424:android:387a2c7da6f5823f71b69d',
    messagingSenderId: '280893152424',
    projectId: 'padchat-4250a',
    storageBucket: 'padchat-4250a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQICcNPjMI6V7uKQuf71GYnMdRuQStPNo',
    appId: '1:280893152424:ios:3f5fb3275f661cfd71b69d',
    messagingSenderId: '280893152424',
    projectId: 'padchat-4250a',
    storageBucket: 'padchat-4250a.appspot.com',
    iosBundleId: 'com.example.padchat',
  );
}
